### ISSUE TITLE
fail to parse array

### ISSUE THREAD

**Issue by thomation** [thomation/Snow-Lang#6]
`a[1] = 2`

```
root : BinaryExpr
---|left : Name: b
---|operator : Operator: =
---|right : AccessArrayMemberStatement
---|---|Object : Name: a
---|---|access_key : NumberLiteral: 1
Traceback (most recent call last):
        21: from test.rb:16:in `<main>'
        20: from C:/codes/Snow/Snow-Lang/Core/Interpreter.rb:19:in `run'
        19: from C:/codes/Snow/Snow-Lang/Core/Parsers.rb:5:in `parse'
        18: from C:/codes/Snow/Snow-Lang/Core/Parser/ProgramParser.rb:16:in `parse'
        17: from C:/codes/Snow/Snow-Lang/Core/Parser/StatementParser.rb:20:in `parse'
        16: from C:/codes/Snow/Snow-Lang/Core/Parser/StatementParser.rb:23:in `parse_simple'
        15: from C:/codes/Snow/Snow-Lang/Core/Parser/SimpleParser.rb:7:in `parse'
        14: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:32:in `parse'
        13: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:49:in `parse_binary'
        12: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:49:in `each'
        11: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:50:in `block in parse_binary'
        10: from C:/codes/Snow/Snow-Lang/Core/Parser/FactorParser.rb:16:in `parse'
         9: from C:/codes/Snow/Snow-Lang/Core/Parser/FactorParser.rb:24:in `parse_primary'
         8: from C:/codes/Snow/Snow-Lang/Core/Parser/PrimaryParser.rb:28:in `parse'
         7: from C:/codes/Snow/Snow-Lang/Core/Parser/PrimaryParser.rb:67:in `parse_id'
         6: from C:/codes/Snow/Snow-Lang/Core/Parser/AccessArrayMemberParser.rb:9:in `parse'
         5: from C:/codes/Snow/Snow-Lang/Core/Parser/AccessArrayMemberParser.rb:13:in `parse_access_key'
         4: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:32:in `parse'
         3: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:53:in `parse_binary'
         2: from C:/codes/Snow/Snow-Lang/Core/Parser/FactorParser.rb:16:in `parse'
         1: from C:/codes/Snow/Snow-Lang/Core/Parser/FactorParser.rb:24:in `parse_primary'
C:/codes/Snow/Snow-Lang/Core/Parser/PrimaryParser.rb:34:in `parse': Cannot parse primary with = (RuntimeError)
```

**Comment by thomation** [comment]
It's a big problem must be fixed by refactor whole parser, passing end index to method.
