### ISSUE TITLE
Fail to parse float number

### ISSUE THREAD

**Issue by thomation** [thomation/Snow-Lang#7]
```
1.5  * 100 + 8
-9 - 8 / 1.6
(5 + 6.3) * 10
```
```
Traceback (most recent call last):
        10: from ./Test.rb:16:in `<main>'
         9: from C:/codes/Snow/Snow-Lang/Core/Interpreter.rb:19:in `run'
         8: from C:/codes/Snow/Snow-Lang/Core/Parsers.rb:5:in `parse'
         7: from C:/codes/Snow/Snow-Lang/Core/Parser/ProgramParser.rb:16:in `parse'
         6: from C:/codes/Snow/Snow-Lang/Core/Parser/StatementParser.rb:20:in `parse'
         5: from C:/codes/Snow/Snow-Lang/Core/Parser/StatementParser.rb:23:in `parse_simple'
         4: from C:/codes/Snow/Snow-Lang/Core/Parser/SimpleParser.rb:7:in `parse'
         3: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:32:in `parse'
         2: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:54:in `parse_binary'
         1: from C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:58:in `create_binary_tree'
C:/codes/Snow/Snow-Lang/Core/Parser/ExprParser.rb:73:in `find_low_prio_op': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by thomation** [comment]
It caused by adding access token of member of class.

**Comment by thomation** [comment]
A sophisticated lexer must be implemented.
